[package]
name = "dependency2015"
version = "0.1.0"
authors = ["bstrie <865233+bstrie@users.noreply.github.com>"]
edition = "2015"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
